### PR TITLE
zh_CN.lang for 1.10 TF5

### PR DESCRIPTION
**Pull request by forestbat**
Oh I hope this time I am right。

### CODE REVIEW

**Comment by KingLemming** [comment]
No, sorry - you're using the wrong localization keys for tools and armor. Please fork from the most recent version of this repo and try again.

**Comment by forestbat** [comment]
@KingLemming The most recent version of this repo （TheCBP）is master，isn't it？

**Comment by Guro2** [comment]
@forestbat yes but those localization keys in zh_cn.lang under `forestbat:master` is out dated, you have to update them before commit.
some of tools can do it in quickly: https://github.com/Meow-J/Mod-Translation-Styleguide

**Comment by forestbat** [comment]
@Iriasu kinglemming has told me my mistake and I can't use lua well so I will update the .lang manually……

**Pull request closed without merging**
